#my自用
[mitm]
hostname = www.guazimanhua.com

[rewrite_local]
#瓜子漫画
# 1. 隐藏 PC 端顶部广告
^https?:\/\/www\.guazimanhua\.com\/chapter\.php url response-body class="desktop-reader-top-ad" response-body class="desktop-reader-top-ad" style="display:none!important;"
# 2. 隐藏移动端顶部 static 广告
^https?:\/\/www\.guazimanhua\.com\/chapter\.php url response-body class="mobile-reader-top-static-ad" response-body class="mobile-reader-top-static-ad" style="display:none!important;"
# 3. 隐藏底部 APP 引导卡片
^https?:\/\/www\.guazimanhua\.com\/chapter\.php url response-body class="reader-app-card" response-body class="reader-app-card" style="display:none!important;"
# 4. 隐藏读完弹出框
^https?:\/\/www\.guazimanhua\.com\/chapter\.php url response-body class="reader-app-download-prompt" response-body class="reader-app-download-prompt" style="display:none!important;"
