#my自用
[mitm]
hostname = www.guazimanhua.com

[rewrite_local]
# 消除移动端及PC端顶部广告、APP推广卡片、阅读完提示APP弹窗
^https?:\/\/www\.guazimanhua\.com\/chapter\.php url response-body (<div class="(mobile-reader-top-static-ad|desktop-reader-top-ad)"[\s\S]*?<\/div>|<section class="(reader-app-card|reader-app-download-prompt)"[\s\S]*?<\/section>) response-body ""
